### ISSUE TITLE
Python bindings fails with "undefined symbol"

### ISSUE THREAD

**Issue by ZetaTwo** [weggli-rs/weggli#68]
I seem to have some problems building the Python bindings on my Ubuntu 22.04 LTS setup. Running the Python test yields the output below. A similar error occurs if I do `python3 setup.py install --user` followed by `python3 -c 'import weggli'`. When another person tried it though it worked so it's not always. Might be something broken with my environment but posting it here for future reference and my debugging efforts.

```
$ python3 setup.py test          
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
running egg_info
writing src/weggli.egg-info/PKG-INFO
writing dependency_links to src/weggli.egg-info/dependency_links.txt
writing top-level names to src/weggli.egg-info/top_level.txt
reading manifest file 'src/weggli.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'src/weggli.egg-info/SOURCES.txt'
running build_ext
running build_rust
cargo rustc --lib --message-format=json-render-diagnostics --manifest-path Cargo.toml -v --features python pyo3/extension-module -- --crate-type cdylib
       Fresh autocfg v1.0.1
       Fresh unicode-xid v0.2.2
       Fresh cfg-if v1.0.0
   Compiling syn v1.0.85
   Compiling proc-macro-hack v0.5.19
     Running `rustc --crate-name build_script_build --edition=2018 /home/zetatwo/.cargo/registry/src/github.com-1ecc6299db9ec823/syn-1.0.85/build.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="clone-impls"' --cfg 'feature="default"' --cfg 'feature="derive"' --cfg 'feature="extra-traits"' --cfg 'feature="full"' --cfg 'feature="parsing"' --cfg 'feature="printing"' --cfg 'feature="proc-macro"' --cfg 'feature="quote"' --cfg 'feature="visit"' -C metadata=5737202938caee8b -C extra-filename=-5737202938caee8b --out-dir /home/zetatwo/Projects/weggli/target/debug/build/syn-5737202938caee8b -L dependency=/home/zetatwo/Projects/weggli/target/debug/deps --cap-lints allow`
     Running `rustc --crate-name build_script_build --edition=2018 /home/zetatwo/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro-hack-0.5.19/build.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 -C metadata=f7ff84a8fe3d13fb -C extra-filename=-f7ff84a8fe3d13fb --out-dir /home/zetatwo/Projects/weggli/target/debug/build/proc-macro-hack-f7ff84a8fe3d13fb -L dependency=/home/zetatwo/Projects/weggli/target/debug/deps --cap-lints allow`
       Fresh scopeguard v1.1.0
       Fresh lazy_static v1.4.0
       Fresh cc v1.0.72
   Compiling parking_lot_core v0.8.5
     Running `rustc --crate-name build_script_build --edition=2018 /home/zetatwo/.cargo/registry/src/github.com-1ecc6299db9ec823/parking_lot_core-0.8.5/build.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 -C metadata=f85214fee3e3ca60 -C extra-filename=-f85214fee3e3ca60 --out-dir /home/zetatwo/Projects/weggli/target/debug/build/parking_lot_core-f85214fee3e3ca60 -L dependency=/home/zetatwo/Projects/weggli/target/debug/deps --cap-lints allow`
   Compiling smallvec v1.7.0
     Running `rustc --crate-name smallvec --edition=2018 /home/zetatwo/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.7.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=9c17253beca91beb -C extra-filename=-9c17253beca91beb --out-dir /home/zetatwo/Projects/weggli/target/debug/deps -L dependency=/home/zetatwo/Projects/weggli/target/debug/deps --cap-lints allow`
   Compiling unindent v0.1.7
     Running `rustc --crate-name unindent --edition=2018 /home/zetatwo/.cargo/registry/src/github.com-1ecc6299db9ec823/unindent-0.1.7/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=95e9640e124853e7 -C extra-filename=-95e9640e124853e7 --out-dir /home/zetatwo/Projects/weggli/target/debug/deps -L dependency=/home/zetatwo/Projects/weggli/target/debug/deps --cap-lints allow`
   Compiling inventory v0.1.11
     Running `rustc --crate-name build_script_build --edition=2018 /home/zetatwo/.cargo/registry/src/github.com-1ecc6299db9ec823/inventory-0.1.11/build.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 -C metadata=4c250073ccd131b2 -C extra-filename=-4c250073ccd131b2 --out-dir /home/zetatwo/Projects/weggli/target/debug/build/inventory-4c250073ccd131b2 -L dependency=/home/zetatwo/Projects/weggli/target/debug/deps --cap-lints allow`
   Compiling pyo3 v0.13.2
     Running `rustc --crate-name build_script_build --edition=2018 /home/zetatwo/.cargo/registry/src/github.com-1ecc6299db9ec823/pyo3-0.13.2/build.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="auto-initialize"' --cfg 'feature="ctor"' --cfg 'feature="default"' --cfg 'feature="extension-module"' --cfg 'feature="indoc"' --cfg 'feature="inventory"' --cfg 'feature="macros"' --cfg 'feature="paste"' --cfg 'feature="pyo3-macros"' --cfg 'feature="unindent"' -C metadata=cb8ee8d4ec596434 -C extra-filename=-cb8ee8d4ec596434 --out-dir /home/zetatwo/Projects/weggli/target/debug/build/pyo3-cb8ee8d4ec596434 -L dependency=/home/zetatwo/Projects/weggli/target/debug/deps --cap-lints allow`
       Fresh unicode-width v0.1.9
       Fresh bitflags v1.3.2
       Fresh regex-syntax v0.6.25
       Fresh either v1.6.1
       Fresh vec_map v0.8.2
       Fresh cfg-if v0.1.10
       Fresh same-file v1.0.6
       Fresh ansi_term v0.12.1
       Fresh void v1.0.2
       Fresh termcolor v1.1.2
       Fresh strsim v0.8.0
       Fresh rustc-hash v1.1.0
   Compiling instant v0.1.12
     Running `rustc --crate-name instant --edition=2018 /home/zetatwo/.cargo/registry/src/github.com-1ecc6299db9ec823/instant-0.1.12/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=dc0183b714626b1c -C extra-filename=-dc0183b714626b1c --out-dir /home/zetatwo/Projects/weggli/target/debug/deps -L dependency=/home/zetatwo/Projects/weggli/target/debug/deps --extern cfg_if=/home/zetatwo/Projects/weggli/target/debug/deps/libcfg_if-fa0d38a03582caa4.rmeta --cap-lints allow`
     Running `/home/zetatwo/Projects/weggli/target/debug/build/syn-5737202938caee8b/build-script-build`
   Compiling lock_api v0.4.5
     Running `rustc --crate-name lock_api --edition=2018 /home/zetatwo/.cargo/registry/src/github.com-1ecc6299db9ec823/lock_api-0.4.5/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=34b0c67f331fd2ed -C extra-filename=-34b0c67f331fd2ed --out-dir /home/zetatwo/Projects/weggli/target/debug/deps -L dependency=/home/zetatwo/Projects/weggli/target/debug/deps --extern scopeguard=/home/zetatwo/Projects/weggli/target/debug/deps/libscopeguard-c988ee37a88938c5.rmeta --cap-lints allow`
   Compiling weggli v0.2.4 (/home/zetatwo/Projects/weggli)
     Running `rustc --crate-name build_script_build --edition=2018 build.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="pyo3"' --cfg 'feature="python"' -C metadata=e9ac922e4610f015 -C extra-filename=-e9ac922e4610f015 --out-dir /home/zetatwo/Projects/weggli/target/debug/build/weggli-e9ac922e4610f015 -C incremental=/home/zetatwo/Projects/weggli/target/debug/incremental -L dependency=/home/zetatwo/Projects/weggli/target/debug/deps --extern cc=/home/zetatwo/Projects/weggli/target/debug/deps/libcc-619d115c76210738.rlib`
     Running `/home/zetatwo/Projects/weggli/target/debug/build/proc-macro-hack-f7ff84a8fe3d13fb/build-script-build`
     Running `/home/zetatwo/Projects/weggli/target/debug/build/parking_lot_core-f85214fee3e3ca60/build-script-build`
     Running `/home/zetatwo/Projects/weggli/target/debug/build/inventory-4c250073ccd131b2/build-script-build`
       Fresh textwrap v0.11.0
       Fresh walkdir v2.3.2
       Fresh libc v0.2.112
       Fresh proc-macro2 v1.0.36
       Fresh crossbeam-utils v0.8.6
       Fresh memchr v2.4.1
     Running `/home/zetatwo/Projects/weggli/target/debug/build/weggli-e9ac922e4610f015/build-script-build`
     Running `rustc --crate-name proc_macro_hack --edition=2018 /home/zetatwo/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro-hack-0.5.19/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type proc-macro --emit=dep-info,link -C prefer-dynamic -C embed-bitcode=no -C debuginfo=2 -C metadata=36581dfd343e8acc -C extra-filename=-36581dfd343e8acc --out-dir /home/zetatwo/Projects/weggli/target/debug/deps -L dependency=/home/zetatwo/Projects/weggli/target/debug/deps --extern proc_macro --cap-lints allow`
       Fresh log v0.4.14
       Fresh memoffset v0.6.5
       Fresh num-traits v0.2.14
       Fresh num_cpus v1.13.1
       Fresh atty v0.2.14
       Fresh time v0.1.44
     Running `rustc --crate-name parking_lot_core --edition=2018 /home/zetatwo/.cargo/registry/src/github.com-1ecc6299db9ec823/parking_lot_core-0.8.5/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=54209c3f614f7cef -C extra-filename=-54209c3f614f7cef --out-dir /home/zetatwo/Projects/weggli/target/debug/deps -L dependency=/home/zetatwo/Projects/weggli/target/debug/deps --extern cfg_if=/home/zetatwo/Projects/weggli/target/debug/deps/libcfg_if-fa0d38a03582caa4.rmeta --extern instant=/home/zetatwo/Projects/weggli/target/debug/deps/libinstant-dc0183b714626b1c.rmeta --extern libc=/home/zetatwo/Projects/weggli/target/debug/deps/liblibc-07f81d1987f627ca.rmeta --extern smallvec=/home/zetatwo/Projects/weggli/target/debug/deps/libsmallvec-9c17253beca91beb.rmeta --cap-lints allow`
       Fresh nix v0.17.0
       Fresh quote v1.0.14
       Fresh crossbeam-channel v0.5.2
       Fresh aho-corasick v0.7.18
     Running `/home/zetatwo/Projects/weggli/target/debug/build/pyo3-cb8ee8d4ec596434/build-script-build`
   Compiling paste-impl v0.1.18
     Running `rustc --crate-name paste_impl --edition=2018 /home/zetatwo/.cargo/registry/src/github.com-1ecc6299db9ec823/paste-impl-0.1.18/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type proc-macro --emit=dep-info,link -C prefer-dynamic -C embed-bitcode=no -C debuginfo=2 -C metadata=175494bd18f9ac70 -C extra-filename=-175494bd18f9ac70 --out-dir /home/zetatwo/Projects/weggli/target/debug/deps -L dependency=/home/zetatwo/Projects/weggli/target/debug/deps --extern proc_macro_hack=/home/zetatwo/Projects/weggli/target/debug/deps/libproc_macro_hack-36581dfd343e8acc.so --extern proc_macro --cap-lints allow`
       Fresh crossbeam-epoch v0.9.6
       Fresh num-integer v0.1.44
       Fresh clap v2.34.0
       Fresh colored v2.0.0
   Compiling parking_lot v0.11.2
     Running `rustc --crate-name parking_lot --edition=2018 /home/zetatwo/.cargo/registry/src/github.com-1ecc6299db9ec823/parking_lot-0.11.2/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' -C metadata=0be689697a3bba97 -C extra-filename=-0be689697a3bba97 --out-dir /home/zetatwo/Projects/weggli/target/debug/deps -L dependency=/home/zetatwo/Projects/weggli/target/debug/deps --extern instant=/home/zetatwo/Projects/weggli/target/debug/deps/libinstant-dc0183b714626b1c.rmeta --extern lock_api=/home/zetatwo/Projects/weggli/target/debug/deps/liblock_api-34b0c67f331fd2ed.rmeta --extern parking_lot_core=/home/zetatwo/Projects/weggli/target/debug/deps/libparking_lot_core-54209c3f614f7cef.rmeta --cap-lints allow`
     Running `rustc --crate-name syn --edition=2018 /home/zetatwo/.cargo/registry/src/github.com-1ecc6299db9ec823/syn-1.0.85/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="clone-impls"' --cfg 'feature="default"' --cfg 'feature="derive"' --cfg 'feature="extra-traits"' --cfg 'feature="full"' --cfg 'feature="parsing"' --cfg 'feature="printing"' --cfg 'feature="proc-macro"' --cfg 'feature="quote"' --cfg 'feature="visit"' -C metadata=13cf818070f8dc37 -C extra-filename=-13cf818070f8dc37 --out-dir /home/zetatwo/Projects/weggli/target/debug/deps -L dependency=/home/zetatwo/Projects/weggli/target/debug/deps --extern proc_macro2=/home/zetatwo/Projects/weggli/target/debug/deps/libproc_macro2-389aadaa5c25aeea.rmeta --extern quote=/home/zetatwo/Projects/weggli/target/debug/deps/libquote-7e54fa6ad85adb38.rmeta --extern unicode_xid=/home/zetatwo/Projects/weggli/target/debug/deps/libunicode_xid-3f4caffb2e0bd218.rmeta --cap-lints allow --cfg syn_disable_nightly_tests`
       Fresh regex v1.5.4
       Fresh crossbeam-deque v0.8.1
       Fresh chrono v0.4.19
   Compiling paste v0.1.18
     Running `rustc --crate-name paste --edition=2018 /home/zetatwo/.cargo/registry/src/github.com-1ecc6299db9ec823/paste-0.1.18/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=1ff2b4e07c7be25e -C extra-filename=-1ff2b4e07c7be25e --out-dir /home/zetatwo/Projects/weggli/target/debug/deps -L dependency=/home/zetatwo/Projects/weggli/target/debug/deps --extern paste_impl=/home/zetatwo/Projects/weggli/target/debug/deps/libpaste_impl-175494bd18f9ac70.so --extern proc_macro_hack=/home/zetatwo/Projects/weggli/target/debug/deps/libproc_macro_hack-36581dfd343e8acc.so --cap-lints allow`
       Fresh tree-sitter v0.20.2
       Fresh rayon-core v1.9.1
       Fresh simplelog v0.10.2
       Fresh rayon v1.5.1
   Compiling pyo3-macros-backend v0.13.2
     Running `rustc --crate-name pyo3_macros_backend --edition=2018 /home/zetatwo/.cargo/registry/src/github.com-1ecc6299db9ec823/pyo3-macros-backend-0.13.2/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=d9e312df010f9610 -C extra-filename=-d9e312df010f9610 --out-dir /home/zetatwo/Projects/weggli/target/debug/deps -L dependency=/home/zetatwo/Projects/weggli/target/debug/deps --extern proc_macro2=/home/zetatwo/Projects/weggli/target/debug/deps/libproc_macro2-389aadaa5c25aeea.rmeta --extern quote=/home/zetatwo/Projects/weggli/target/debug/deps/libquote-7e54fa6ad85adb38.rmeta --extern syn=/home/zetatwo/Projects/weggli/target/debug/deps/libsyn-13cf818070f8dc37.rmeta --cap-lints allow`
   Compiling indoc-impl v0.3.6
   Compiling inventory-impl v0.1.11
     Running `rustc --crate-name indoc_impl --edition=2018 /home/zetatwo/.cargo/registry/src/github.com-1ecc6299db9ec823/indoc-impl-0.3.6/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type proc-macro --emit=dep-info,link -C prefer-dynamic -C embed-bitcode=no -C debuginfo=2 -C metadata=0826074e9c4ae085 -C extra-filename=-0826074e9c4ae085 --out-dir /home/zetatwo/Projects/weggli/target/debug/deps -L dependency=/home/zetatwo/Projects/weggli/target/debug/deps --extern proc_macro_hack=/home/zetatwo/Projects/weggli/target/debug/deps/libproc_macro_hack-36581dfd343e8acc.so --extern proc_macro2=/home/zetatwo/Projects/weggli/target/debug/deps/libproc_macro2-389aadaa5c25aeea.rlib --extern quote=/home/zetatwo/Projects/weggli/target/debug/deps/libquote-7e54fa6ad85adb38.rlib --extern syn=/home/zetatwo/Projects/weggli/target/debug/deps/libsyn-13cf818070f8dc37.rlib --extern unindent=/home/zetatwo/Projects/weggli/target/debug/deps/libunindent-95e9640e124853e7.rlib --extern proc_macro --cap-lints allow`
     Running `rustc --crate-name inventory_impl --edition=2018 /home/zetatwo/.cargo/registry/src/github.com-1ecc6299db9ec823/inventory-impl-0.1.11/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type proc-macro --emit=dep-info,link -C prefer-dynamic -C embed-bitcode=no -C debuginfo=2 -C metadata=a59475fd41b92be4 -C extra-filename=-a59475fd41b92be4 --out-dir /home/zetatwo/Projects/weggli/target/debug/deps -L dependency=/home/zetatwo/Projects/weggli/target/debug/deps --extern proc_macro2=/home/zetatwo/Projects/weggli/target/debug/deps/libproc_macro2-389aadaa5c25aeea.rlib --extern quote=/home/zetatwo/Projects/weggli/target/debug/deps/libquote-7e54fa6ad85adb38.rlib --extern syn=/home/zetatwo/Projects/weggli/target/debug/deps/libsyn-13cf818070f8dc37.rlib --extern proc_macro --cap-lints allow`
   Compiling ctor v0.1.21
     Running `rustc --crate-name ctor --edition=2018 /home/zetatwo/.cargo/registry/src/github.com-1ecc6299db9ec823/ctor-0.1.21/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type proc-macro --emit=dep-info,link -C prefer-dynamic -C embed-bitcode=no -C debuginfo=2 -C metadata=fe9715a5eb5b39de -C extra-filename=-fe9715a5eb5b39de --out-dir /home/zetatwo/Projects/weggli/target/debug/deps -L dependency=/home/zetatwo/Projects/weggli/target/debug/deps --extern quote=/home/zetatwo/Projects/weggli/target/debug/deps/libquote-7e54fa6ad85adb38.rlib --extern syn=/home/zetatwo/Projects/weggli/target/debug/deps/libsyn-13cf818070f8dc37.rlib --extern proc_macro --cap-lints allow`
   Compiling ghost v0.1.2
     Running `rustc --crate-name ghost --edition=2018 /home/zetatwo/.cargo/registry/src/github.com-1ecc6299db9ec823/ghost-0.1.2/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type proc-macro --emit=dep-info,link -C prefer-dynamic -C embed-bitcode=no -C debuginfo=2 -C metadata=04ae0cc4d2fd97fc -C extra-filename=-04ae0cc4d2fd97fc --out-dir /home/zetatwo/Projects/weggli/target/debug/deps -L dependency=/home/zetatwo/Projects/weggli/target/debug/deps --extern proc_macro2=/home/zetatwo/Projects/weggli/target/debug/deps/libproc_macro2-389aadaa5c25aeea.rlib --extern quote=/home/zetatwo/Projects/weggli/target/debug/deps/libquote-7e54fa6ad85adb38.rlib --extern syn=/home/zetatwo/Projects/weggli/target/debug/deps/libsyn-13cf818070f8dc37.rlib --extern proc_macro --cap-lints allow`
   Compiling pyo3-macros v0.13.2
     Running `rustc --crate-name pyo3_macros --edition=2018 /home/zetatwo/.cargo/registry/src/github.com-1ecc6299db9ec823/pyo3-macros-0.13.2/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type proc-macro --emit=dep-info,link -C prefer-dynamic -C embed-bitcode=no -C debuginfo=2 -C metadata=d3adc766305a7f5f -C extra-filename=-d3adc766305a7f5f --out-dir /home/zetatwo/Projects/weggli/target/debug/deps -L dependency=/home/zetatwo/Projects/weggli/target/debug/deps --extern pyo3_macros_backend=/home/zetatwo/Projects/weggli/target/debug/deps/libpyo3_macros_backend-d9e312df010f9610.rlib --extern quote=/home/zetatwo/Projects/weggli/target/debug/deps/libquote-7e54fa6ad85adb38.rlib --extern syn=/home/zetatwo/Projects/weggli/target/debug/deps/libsyn-13cf818070f8dc37.rlib --extern proc_macro --cap-lints allow`
   Compiling indoc v0.3.6
     Running `rustc --crate-name indoc --edition=2018 /home/zetatwo/.cargo/registry/src/github.com-1ecc6299db9ec823/indoc-0.3.6/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=170156cc1a7b9c76 -C extra-filename=-170156cc1a7b9c76 --out-dir /home/zetatwo/Projects/weggli/target/debug/deps -L dependency=/home/zetatwo/Projects/weggli/target/debug/deps --extern indoc_impl=/home/zetatwo/Projects/weggli/target/debug/deps/libindoc_impl-0826074e9c4ae085.so --extern proc_macro_hack=/home/zetatwo/Projects/weggli/target/debug/deps/libproc_macro_hack-36581dfd343e8acc.so --cap-lints allow`
     Running `rustc --crate-name inventory --edition=2018 /home/zetatwo/.cargo/registry/src/github.com-1ecc6299db9ec823/inventory-0.1.11/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=966b134369e7408f -C extra-filename=-966b134369e7408f --out-dir /home/zetatwo/Projects/weggli/target/debug/deps -L dependency=/home/zetatwo/Projects/weggli/target/debug/deps --extern ctor=/home/zetatwo/Projects/weggli/target/debug/deps/libctor-fe9715a5eb5b39de.so --extern ghost=/home/zetatwo/Projects/weggli/target/debug/deps/libghost-04ae0cc4d2fd97fc.so --extern inventory_impl=/home/zetatwo/Projects/weggli/target/debug/deps/libinventory_impl-a59475fd41b92be4.so --cap-lints allow`
     Running `rustc --crate-name pyo3 --edition=2018 /home/zetatwo/.cargo/registry/src/github.com-1ecc6299db9ec823/pyo3-0.13.2/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="auto-initialize"' --cfg 'feature="ctor"' --cfg 'feature="default"' --cfg 'feature="extension-module"' --cfg 'feature="indoc"' --cfg 'feature="inventory"' --cfg 'feature="macros"' --cfg 'feature="paste"' --cfg 'feature="pyo3-macros"' --cfg 'feature="unindent"' -C metadata=b62146b9735b1e6d -C extra-filename=-b62146b9735b1e6d --out-dir /home/zetatwo/Projects/weggli/target/debug/deps -L dependency=/home/zetatwo/Projects/weggli/target/debug/deps --extern cfg_if=/home/zetatwo/Projects/weggli/target/debug/deps/libcfg_if-fa0d38a03582caa4.rmeta --extern ctor=/home/zetatwo/Projects/weggli/target/debug/deps/libctor-fe9715a5eb5b39de.so --extern indoc=/home/zetatwo/Projects/weggli/target/debug/deps/libindoc-170156cc1a7b9c76.rmeta --extern inventory=/home/zetatwo/Projects/weggli/target/debug/deps/libinventory-966b134369e7408f.rmeta --extern libc=/home/zetatwo/Projects/weggli/target/debug/deps/liblibc-07f81d1987f627ca.rmeta --extern parking_lot=/home/zetatwo/Projects/weggli/target/debug/deps/libparking_lot-0be689697a3bba97.rmeta --extern paste=/home/zetatwo/Projects/weggli/target/debug/deps/libpaste-1ff2b4e07c7be25e.rmeta --extern pyo3_macros=/home/zetatwo/Projects/weggli/target/debug/deps/libpyo3_macros-d3adc766305a7f5f.so --extern unindent=/home/zetatwo/Projects/weggli/target/debug/deps/libunindent-95e9640e124853e7.rmeta --cap-lints allow --cfg Py_SHARED --cfg Py_3_6 --cfg Py_3_7 --cfg Py_3_8 --cfg Py_3_9 --cfg Py_3_10 --cfg 'py_sys_config="WITH_THREAD"'`
     Running `rustc --crate-name weggli --edition=2018 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type rlib --crate-type dylib --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 --crate-type cdylib --cfg 'feature="pyo3"' --cfg 'feature="python"' -C metadata=bac47e802d24988f --out-dir /home/zetatwo/Projects/weggli/target/debug/deps -C incremental=/home/zetatwo/Projects/weggli/target/debug/incremental -L dependency=/home/zetatwo/Projects/weggli/target/debug/deps --extern clap=/home/zetatwo/Projects/weggli/target/debug/deps/libclap-b3367e576e67dfe3.rlib --extern colored=/home/zetatwo/Projects/weggli/target/debug/deps/libcolored-28846ee9869253bc.rlib --extern log=/home/zetatwo/Projects/weggli/target/debug/deps/liblog-a402241ae309561f.rlib --extern nix=/home/zetatwo/Projects/weggli/target/debug/deps/libnix-2b057218735fb323.rlib --extern pyo3=/home/zetatwo/Projects/weggli/target/debug/deps/libpyo3-b62146b9735b1e6d.rlib --extern rayon=/home/zetatwo/Projects/weggli/target/debug/deps/librayon-4bd54a8f6a505307.rlib --extern regex=/home/zetatwo/Projects/weggli/target/debug/deps/libregex-4d86d90d817f153a.rlib --extern rustc_hash=/home/zetatwo/Projects/weggli/target/debug/deps/librustc_hash-062a375220cbcbba.rlib --extern simplelog=/home/zetatwo/Projects/weggli/target/debug/deps/libsimplelog-39cf1ecb22e7fbb2.rlib --extern tree_sitter=/home/zetatwo/Projects/weggli/target/debug/deps/libtree_sitter-c3e12a65db9ead5e.rlib --extern walkdir=/home/zetatwo/Projects/weggli/target/debug/deps/libwalkdir-78a2d3854b534f47.rlib -L native=/home/zetatwo/Projects/weggli/target/debug/build/weggli-2cc0bc4d0f1a0cf5/out -L native=/home/zetatwo/Projects/weggli/target/debug/build/weggli-2cc0bc4d0f1a0cf5/out -L native=/home/zetatwo/Projects/weggli/target/debug/build/weggli-2cc0bc4d0f1a0cf5/out -l static=tree-sitter-c -l static=tree-sitter-cpp-scanner -l stdc++ -l static=tree-sitter-cpp-parser -L native=/home/zetatwo/Projects/weggli/target/debug/build/tree-sitter-6cd8dc0e956750fc/out`
    Finished dev [unoptimized + debuginfo] target(s) in 19.17s
Copying rust artifact from /home/zetatwo/Projects/weggli/target/debug/libweggli.so to /home/zetatwo/Projects/weggli/src/weggli.cpython-310-x86_64-linux-gnu.so
tests (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests
Traceback (most recent call last):
  File "/usr/lib/python3.10/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/zetatwo/Projects/weggli/tests/__init__.py", line 2, in <module>
    import weggli
ImportError: /home/zetatwo/Projects/weggli/src/weggli.cpython-310-x86_64-linux-gnu.so: undefined symbol: tree_sitter_cpp_external_scanner_create


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
Test failed: <unittest.runner.TextTestResult run=1 errors=1 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=1 errors=1 failures=0>
```

**Comment by felixwilhelm** [comment]
Can you try to build with rustc 1.60.0 ? It looks like a change in 1.61.0 broke the Python build: https://github.com/rust-lang/rust/blob/1.61.0/RELEASES.md#compatibility-notes

**Comment by ZetaTwo** [comment]
Yup, this seems to be the problem. 1.60.0 works, 1.61.0 fails. So we need to change some details about how the linking is done?
